### ISSUE TITLE
LDO

### ISSUE THREAD

**Issue by Hasi123** [ricardozago/GY91-MPU9250-BMP280#1]
Hi,
Could you also provide some information, maybe a datasheet for the LDO? And is the 3V3 pin on the GY91 also an output?

Thanks in advance,
David

**Comment by ricardozago** [comment]
In my S2PJ is written, putting in google, the first result is:
http://www.ti.com/lit/ds/symlink/lp2983.pdf

I did not understand the reason, since there is no such text in the document.

A photo of the LDO:

! [https://img.mysku-st.ru/uploads/images/05/34/98/2017/08/14/cf70dc.jpg] (S2PJ)

The TI datasheet is 150 mA. Without a heatsink, considering what other chips already consume, you may have a problem.

It depends on your project.

**Comment by ricardozago** [comment]
In my S2PJ is written, putting in google, the first result is:
[http://www.ti.com/lit/ds/symlink/lp2983.pdf](http://www.ti.com/lit/ds/symlink/lp2983.pdf)

I did not understand the reason, since there is no such text in the document.

A photo of the LDO:

![S2PJ](https://img.mysku-st.ru/uploads/images/05/34/98/2017/08/14/cf70dc.jpg)

The TI datasheet is 150 mA. Without a heatsink, considering what other chips already consume, you may have a problem.

It depends on your project.

**Comment by Hasi123** [comment]
Thanks!
